<a href="https://colab.research.google.com/github/Daeijavad/Machine_Learning_HW/blob/main/HW4_LinearRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Q1

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
X = pd.read_csv("tak4data.csv", index_col = "order")
t = X["mark"]
X = X.drop(["mark"], axis=1)

# Q2

In [ ]:
moore_penrose = np.dot(np.linalg.inv(np.dot(X.values.T,X.values)),X.values.T)
Wml = np.dot(moore_penrose,t)
Wml

array([0.3 , 0.3 , 0.05, 0.05, 0.15, 0.15])

In [ ]:
y = np.dot(X,Wml)
y

array([20.  , 14.8 , 18.35, 12.75, 16.  , 15.8 , 15.75, 15.05, 17.4 ,
       12.2 ,  8.6 , 12.45, 10.9 ,  9.8 ,  6.85,  6.5 , 10.25, 10.3 ,
       11.4 ,  6.35])

In [ ]:
data_test = [[8.25,10.5,16.75,14.25,13.5,17.25],
             [17,18,6.75,7,12.5,7],
             [14.5,12,10,9,20,4],
             [13,18,15,15.25,15.25,16],
             [18.5,19.75,7,8.5,9.75,16.25]]

mark_test = np.dot(data_test,Wml)
mark_test

array([11.7875, 14.1125, 12.5   , 15.5   , 16.15  ])

# Q3

In [ ]:
import sklearn.linear_model

In [ ]:
regresion = sklearn.linear_model.LinearRegression()
regresion.fit(X,t)
regresion.coef_

array([0.3 , 0.3 , 0.05, 0.05, 0.15, 0.15])